version: "3.4"
services:
    web:
        build: .
        ports:
            - "8090:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:2017-CU8"
        environment:
            SA_PASSWORD: "@fERMAT!"
            ACCEPT_EULA: "Y"
        ports:
            - '1455:1433'